"""Adding SavedTranslation table

Revision ID: bfb6d264f553
Revises: 1ca9a985ee6f
Create Date: 2024-09-05 10:43:55.973763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb6d264f553'
down_revision = '1ca9a985ee6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedTranslations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hindiWord', sa.String(), nullable=True),
    sa.Column('englishTranslations', sa.Text(), nullable=True),
    sa.Column('dateCreated', sa.DateTime(), nullable=True),
    sa.Column('pastInput_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pastInput_id'], ['pastInputs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('savedTranslations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savedTranslations_dateCreated'), ['dateCreated'], unique=False)

    with op.batch_alter_table('pastInputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pastInputs_dateCreated'), ['dateCreated'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('pastInputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pastInputs_dateCreated'))

    with op.batch_alter_table('savedTranslations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savedTranslations_dateCreated'))

    op.drop_table('savedTranslations')
    # ### end Alembic commands ###
